### PR TITLE
Add support for hashed passwords

### PR DESCRIPTION
**Pull request by wanieru**
Based on: #873

I added support for both supplying hashed passwords into `ftpserver.json`, but also a config option `hash_plaintext_passwords`, which when loading a config will check if any passwords are plaintext, and re-encode the json-file after hashing them.

### CODE REVIEW

**Comment by wanieru** [comment]
With the option to automatically hash plain-text passwords, running the server will neatly transform ftpserver.json like this, without breaking any formatting or changing/adding any other properties:
```json
{
  "version": 1,
  "accesses": [
    {
      "user": "test",
      "pass": "test",
      "fs": "os",
      "params": {
        "basePath": "/tmp"
      }
    }
  ],
  "hash_plaintext_passwords": true,
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  }
}
```
↓↓↓
```json
{
  "version": 1,
  "accesses": [
    {
      "user": "test",
      "pass": "$2a$10$xD02IYP4PnlOV1k6wxioluwj2q9JfVxikHho0hRdDcHJCS.iCodHC",
      "fs": "os",
      "params": {
        "basePath": "/tmp"
      }
    }
  ],
  "hash_plaintext_passwords": true,
  "passive_transfer_port_range": {
    "start": 2122,
    "end": 2130
  }
}
```

**Review by fclairamb — APPROVED** [review]
Thank you @wanieru, I really like how you implemented it.

**Comment by wanieru** [comment]
> Thank you @wanieru, I really like how you implemented it.

Thank you!

**Comment by SuperQ** [comment]
You might be interested in how we [implemented a cache for bcrypt](https://github.com/prometheus/exporter-toolkit/blob/c5c3d5b0795fa4c966ae58875afec476e832ac4e/web/handler.go#L108-L138) to reduce connection times for repeated access.

**Pull request merged**
